# Generated by Django 3.0.5 on 2022-10-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220929_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='conf_code',
        ),
    ]
